language: c
sudo: required
os:
  - linux
  - osx
env:
  matrix:
    - OCAML_VERSION=4.02 EXTRA_DEPS="oasis"
    - OCAML_VERSION=4.01 EXTRA_DEPS="oasis"

script: bash -ex .travis-ci.sh

notifications:
  email:
    - Christophe.Troestler@umons.ac.be
