# http://www.appveyor.com/docs/appveyor-yml

platform:
  - x64

branches:
  only:
    - master
    - appv

# Do a shallow clone of the repo to speed up the build
clone_depth: 1

install:
  - appveyor DownloadFile "https://raw.githubusercontent.com/Chris00/ocaml-appveyor/master/install_ocaml.cmd" -FileName "C:\install_ocaml.cmd"
  - C:\install_ocaml.cmd
  - appveyor DownloadFile "https://raw.githubusercontent.com/Chris00/ocaml-appveyor/master/install_oasis_pkg.ml"
  - ocaml install_oasis_pkg.ml https://github.com/Chris00/cppo/archive/ef5cf96e90009bc6c8035e348c5d043fb5159905.tar.gz
  - ocamlc -version

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - ocaml setup.ml -configure
  - ocaml setup.ml -build
  - ocaml setup.ml -install
