# http://www.appveyor.com/docs/appveyor-yml

platform:
  - x64

environment:
  global:
    PACKAGE: mindstorm
    CYG_ROOT: "C:\\cygwin"
    CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
    FORK_USER: Chris00

init:
  - 'echo System architecture: %PLATFORM%'

install:
  - appveyor DownloadFile https://raw.githubusercontent.com/%FORK_USER%/ocaml-ci-scripts/master/appveyor-opam.sh
  - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P rsync -P patch -P make -P unzip -P git -P perl -P mingw64-x86_64-gcc-core -P jq"

build_script:
  - "%CYG_BASH% '${APPVEYOR_BUILD_FOLDER}/appveyor-opam.sh'"
