#!/bin/sh

IMG='<br /><br /><br />\
<a href="http://sourceforge.net"><img class="sf_logo" \
  src="http://sflogo.sourceforge.net/sflogo.php?group_id=208592\&type=2" \
  width="125" height="37" border="0" alt="SourceForge.net Logo" /></a> \
</body>'

for f in doc/*.html; do
sed -e "s+</body>+$IMG+" $f > $f.tmp
mv $f.tmp $f
done