#define CLAIMEVEN       1
#define BASEINVERSE     2
#define VERTICAL        3
#define AFTEREVEN       4
#define LOWINVERSE      5
#define HIGHINVERSE     6
#define BASECLAIM       7
#define BEFORE          8
#define SPECIALBEFORE   9
