# Makefile for Unix					-*-makefile-gmake-*-
STUBS=mindstorm_unix.c

CC_LIB=-lbluetooth
EXT_O=.o

ifdef D_HAS_USB
  CC_LIB+=-lusb-1.0
endif

INSTALL_FILES += libmindstorm.a dllmindstorm.so

mindstorm.cma: $(STUBS:.c=.o) mindstorm.cmo
	$(OCAMLMKLIB) -o mindstorm  $^ $(CC_LIB)
# 	$(OCAMLC) -a -o $@ $(OCAMLC_FLAGS) -custom unix.cma \
# 	  -I $(OCAMLLIBDIR) -cclib -lbluetooth unix.cma $^

mindstorm.cmxa: $(STUBS:.c=.o) mindstorm.cmx
	$(OCAMLMKLIB) -o mindstorm  $^ $(CC_LIB)


clean::
	-$(RM) *.so
